import{useEffect,useMemo,useState}from'react';
import{Edit3,Plus,Power,ShieldCheck,Trash2}from'lucide-react';
import api from'../../services/api';
import{Btn,Modal,Spinner,Status,Toast}from'../../components/UI';

const img='https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1200&q=80';
function FormModal({kind,open,onClose,onSaved,initial,sports,facilities}){
 const isSport=kind==='sports',isFacility=kind==='facilities',isSlot=kind==='slots',isPlan=kind==='memberships';
 const blank=isSport?{name:'',description:'',image_url:img,price:500,duration_minutes:60,is_active:true}:isFacility?{name:'',sport_id:sports?.[0]?.id||'',capacity:10,price:800,description:'',image_url:img,is_active:true}:isSlot?{facility_id:facilities?.[0]?.id||'',start_time:'06:00',end_time:'07:00',is_available:true}:{name:'',price:1999,duration_days:30,benefits:'Priority booking\nMember rates\nClub events',is_active:true};
 const [form,setForm]=useState(initial||blank);useEffect(()=>setForm(initial||blank),[initial,open,kind]);
 const save=async e=>{e.preventDefault();const body={...form};if(isFacility||isSlot)body.facility_id=Number(body.facility_id);if(isFacility)body.sport_id=Number(body.sport_id);if(isSport)body.price=Number(body.price),body.duration_minutes=Number(body.duration_minutes);if(isPlan)body.price=Number(body.price),body.duration_days=Number(body.duration_days);try{if(initial){await api.put(`/${kind==='memberships'?'memberships/plans':kind}/${initial.id}`,body)}else{await api.post(`/${kind==='memberships'?'memberships/plans':kind}`,body)}onSaved();onClose()}catch(err){alert(err.response?.data?.message||'Could not save record.')}};
 return <Modal open={open} onClose={onClose} title={`${initial?'Edit':'Add'} ${isSport?'sport':isFacility?'facility':isSlot?'time slot':'membership plan'}`}><form className="form-grid" onSubmit={save}>
  {!isSlot&&<Field label="Name" value={form.name} onChange={v=>setForm({...form,name:v})}/>}
  {isFacility&&<Field label="Sport" as="select" options={sports.map(s=>[s.id,s.name])} value={form.sport_id} onChange={v=>setForm({...form,sport_id:v})}/>} 
  {isSlot&&<><Field label="Facility" as="select" options={facilities.map(f=>[f.id,`${f.name} · ${f.sport_name||''}`])} value={form.facility_id} onChange={v=>setForm({...form,facility_id:v})}/><Field label="Start" type="time" value={form.start_time} onChange={v=>setForm({...form,start_time:v})}/><Field label="End" type="time" value={form.end_time} onChange={v=>setForm({...form,end_time:v})}/></>}
  {isSport&&<><Field label="Price" type="number" value={form.price} onChange={v=>setForm({...form,price:v})}/><Field label="Duration (minutes)" type="number" value={form.duration_minutes} onChange={v=>setForm({...form,duration_minutes:v})}/><Field label="Image URL" className="full" value={form.image_url} onChange={v=>setForm({...form,image_url:v})}/></>}
  {isFacility&&<><Field label="Capacity" type="number" value={form.capacity} onChange={v=>setForm({...form,capacity:v})}/><Field label="Price" type="number" value={form.price} onChange={v=>setForm({...form,price:v})}/><Field label="Image URL" className="full" value={form.image_url} onChange={v=>setForm({...form,image_url:v})}/></>}
  {isPlan&&<><Field label="Price" type="number" value={form.price} onChange={v=>setForm({...form,price:v})}/><Field label="Duration (days)" type="number" value={form.duration_days} onChange={v=>setForm({...form,duration_days:v})}/><Field label="Benefits (one per line)" as="textarea" className="full" value={form.benefits} onChange={v=>setForm({...form,benefits:v})}/></>}
  {!isSlot&&!isPlan&&<Field label="Description" as="textarea" className="full" value={form.description} onChange={v=>setForm({...form,description:v})}/>}<label className="check full"><input type="checkbox" checked={isSlot?form.is_available:form.is_active} onChange={e=>setForm({...form,[isSlot?'is_available':'is_active']:e.target.checked})}/> Active / available</label><div className="modal-actions full"><button type="button" className="secondary" onClick={onClose}>Cancel</button><Btn>{initial?'Save changes':'Create record'}</Btn></div>
 </form></Modal>
}
function Field({label,value,onChange,type='text',as='input',options=[],className=''}){return <label className={`field ${className}`}>{label}{as==='select'?<select className="input" value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select>:as==='textarea'?<textarea className="input textarea" rows="4" value={value} onChange={e=>onChange(e.target.value)}/>:<input className="input" type={type} value={value} onChange={e=>onChange(e.target.value)}/>}</label>}

export function SportsAdmin(){const[rows,setRows]=useState(),[open,setOpen]=useState(false),[selected,setSelected]=useState(),[toast,setToast]=useState();const load=()=>api.get('/sports').then(r=>setRows(r.data));useEffect(load,[]);const toggle=async r=>{await api.delete(`/sports/${r.id}`);setToast({message:'Sport deactivated.'});load()};if(!rows)return <Spinner/>;return <Crud title="Sports catalog" eyebrow="CONFIGURATION" description="Control sports, session duration, pricing and customer-facing content." add="Add sport" onAdd={()=>{setSelected(null);setOpen(true)}} rows={rows} columns={[['Sport',r=><><b>{r.name}</b><div className="sub">{r.description}</div></>],['Price',r=>`₹${Number(r.price).toLocaleString('en-IN')}`],['Duration',r=>`${r.duration_minutes} min`],['Status',r=><Status value={r.is_active?'ACTIVE':'INACTIVE'}/>,]]} actions={(r)=><><button className="icon-btn" onClick={()=>{setSelected(r);setOpen(true)}}><Edit3 size={15}/></button><button className="icon-btn" onClick={()=>toggle(r)}><Power size={15}/></button></>}><FormModal kind="sports" open={open} onClose={()=>setOpen(false)} onSaved={()=>{load();setToast({message:'Sport saved.'})}} initial={selected}/><Toast toast={toast} onClose={()=>setToast(null)}/></Crud>}

export function FacilitiesAdmin(){const[rows,setRows]=useState(),[sports,setSports]=useState([]),[open,setOpen]=useState(false),[selected,setSelected]=useState(),[toast,setToast]=useState();const load=()=>api.get('/facilities').then(r=>setRows(r.data));useEffect(()=>{load();api.get('/sports').then(r=>setSports(r.data))},[]);const toggle=async r=>{await api.delete(`/facilities/${r.id}`);setToast({message:'Facility deactivated.'});load()};if(!rows)return <Spinner/>;return <Crud title="Facility management" eyebrow="CAPACITY & VENUES" description="Manage courts, turfs and grounds with sport mapping and pricing." add="Add facility" onAdd={()=>{setSelected(null);setOpen(true)}} rows={rows} columns={[['Facility',r=><><b>{r.name}</b><div className="sub">{r.sport_name}</div></>],['Capacity',r=>r.capacity],['Price',r=>`₹${Number(r.price).toLocaleString('en-IN')}`],['Status',r=><Status value={r.is_active?'ACTIVE':'INACTIVE'}/>]]} actions={(r)=><><button className="icon-btn" onClick={()=>{setSelected(r);setOpen(true)}}><Edit3 size={15}/></button><button className="icon-btn" onClick={()=>toggle(r)}><Power size={15}/></button></>}><FormModal kind="facilities" sports={sports} open={open} onClose={()=>setOpen(false)} onSaved={()=>{load();setToast({message:'Facility saved.'})}} initial={selected}/><Toast toast={toast} onClose={()=>setToast(null)}/></Crud>}

export function SlotsAdmin(){const[rows,setRows]=useState(),[facilities,setFacilities]=useState([]),[open,setOpen]=useState(false),[selected,setSelected]=useState(),[toast,setToast]=useState(),[block,setBlock]=useState({time_slot_id:'',blocked_date:'',reason:'Maintenance'});const load=()=>api.get('/slots').then(r=>setRows(r.data));useEffect(()=>{load();api.get('/facilities').then(r=>setFacilities(r.data))},[]);const disable=async id=>{await api.delete(`/slots/${id}`);setToast({message:'Time slot disabled.'});load()};const blockIt=async e=>{e.preventDefault();try{await api.post('/slots/block',block);setToast({message:'Slot blocked for selected date.'});setBlock({time_slot_id:'',blocked_date:'',reason:'Maintenance'});load()}catch(e){setToast({type:'error',message:e.response?.data?.message||'Could not block slot.'})}};if(!rows)return <Spinner/>;return <><Crud title="Time-slot management" eyebrow="SCHEDULING" description="Configure recurring slot windows and block specific dates for maintenance." add="Add slot" onAdd={()=>{setSelected(null);setOpen(true)}} rows={rows} columns={[['Facility',r=><><b>{r.facility_name}</b><div className="sub">{r.sport_name}</div></>],['Time',r=>`${r.start_time}–${r.end_time}`],['Availability',r=><Status value={r.is_available?'ACTIVE':'INACTIVE'}/>]]} actions={r=><><button className="icon-btn" onClick={()=>{setSelected(r);setOpen(true)}}><Edit3 size={15}/></button><button className="icon-btn" onClick={()=>disable(r.id)}><Power size={15}/></button></>}/><section className="panel block-panel"><div className="section-head"><div><small>MAINTENANCE</small><h2>Block a slot on a date</h2></div></div><form className="form-inline" onSubmit={blockIt}><select className="input" value={block.time_slot_id} onChange={e=>setBlock({...block,time_slot_id:e.target.value})}><option value="">Select slot</option>{rows.map(r=><option key={r.id} value={r.id}>{r.facility_name} · {r.start_time}–{r.end_time}</option>)}</select><input className="input" type="date" value={block.blocked_date} onChange={e=>setBlock({...block,blocked_date:e.target.value})}/><input className="input" placeholder="Reason" value={block.reason} onChange={e=>setBlock({...block,reason:e.target.value})}/><button className="secondary">Block date</button></form></section><FormModal kind="slots" facilities={facilities} open={open} onClose={()=>setOpen(false)} onSaved={()=>{load();setToast({message:'Time slot saved.'})}} initial={selected}/><Toast toast={toast} onClose={()=>setToast(null)}/></>}

export function MembershipsAdmin(){const[rows,setRows]=useState(),[open,setOpen]=useState(false),[selected,setSelected]=useState(),[toast,setToast]=useState();const[plans,setPlans]=useState([]);const load=()=>Promise.all([api.get('/memberships/admin'),api.get('/memberships/plans/admin')]).then(([m,p])=>{setRows(m.data);setPlans(p.data)});useEffect(load,[]);if(!rows)return <Spinner/>;return <div><div className="page-head"><div><small>MEMBERSHIP</small><h1>Plans & member subscriptions</h1><p>Maintain commercial plans and review active membership history.</p></div><button className="primary" onClick={()=>{setSelected(null);setOpen(true)}}><Plus size={16}/> Add plan</button></div><div className="admin-subgrid"><div className="panel"><div className="section-head"><div><small>PLANS</small><h2>Membership catalog</h2></div></div><div className="mini-grid">{plans.map(p=><div className="metric-box wide" key={p.id}><b>{p.name}</b><strong>₹{Number(p.price).toLocaleString('en-IN')}</strong><span>{p.duration_days} days · {p.is_active?'Active':'Inactive'}</span><button className="secondary" onClick={()=>{setSelected(p);setOpen(true)}}>Edit</button></div>)}</div></div><div className="panel table-wrap"><table><thead><tr><th>Member</th><th>Plan</th><th>Start</th><th>End</th><th>Status</th></tr></thead><tbody>{rows.map(m=><tr key={m.id}><td><b>{m.user_name}</b><div className="sub">{m.email}</div></td><td>{m.plan_name}</td><td>{String(m.start_date).slice(0,10)}</td><td>{String(m.end_date).slice(0,10)}</td><td><Status value={m.status}/></td></tr>)}</tbody></table></div></div><FormModal kind="memberships" open={open} onClose={()=>setOpen(false)} onSaved={()=>{load();setToast({message:'Membership plan saved.'})}} initial={selected}/><Toast toast={toast} onClose={()=>setToast(null)}/></div>}

function Crud({title,eyebrow,description,add,onAdd,rows,columns,actions,children}){return <div><div className="page-head"><div><small>{eyebrow}</small><h1>{title}</h1><p>{description}</p></div><button className="primary" onClick={onAdd}><Plus size={16}/> {add}</button></div><div className="panel table-wrap"><table><thead><tr>{columns.map(([h])=><th key={h}>{h}</th>)}<th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{columns.map(([h,render])=><td key={h}>{render(r)}</td>)}<td><div className="row-actions">{actions(r)}</div></td></tr>)}</tbody></table>{!rows.length&&<div className="empty">No records yet.</div>}</div>{children}</div>}
